name: Deploy-To-Server
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Install Deps
      run: sudo apt-get install sshpass
    - name: Actual deploy
      run: |
          sshpass -p '${{ secrets.SERVER_PASS }}' ssh -v -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} <<'ENDSSH'
          set -e
          echo "go to run_tree"
          cd '${{ secrets.SERVER_RUN_PATH }}'
          echo "Pull"
          bash ./github_pull.sh
          echo "Build"
          bash ./github_build.sh
          echo "Run"
          bash ./github_run.sh
          exit 0
          ENDSSH
          
